version: "3"

services:
  front:
    container_name: front
    build: ./front/
    ports:
      - "80:80"
    restart: unless-stopped


  back:
    container_name: back
    build: ./back/
    ports:
      - "8000:4000"
      - "8001:4001"
    restart: unless-stopped
    volumes:
      - taskmaster:/app/files

volumes:
  taskmaster: